import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./utils/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    // absolute:'',
    default: "CWWYH",
    template: "%s | CWWYH",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-app-background h-screen">
        <Providers>
          <Navbar />
          {
            <div className="">
              <ToastContainer />
              {children}
            </div>
          }
        </Providers>
      </body>
    </html>
  );
}
